package main

import (
	"bufio"
	"context"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"flag"
	"fmt"
	"github.com/Ucok23/rekam/internal/updatecheck"
	"net/http"
	"os"
	"os/exec"
	"os/signal"
	"os/user"
	"path/filepath"
	"runtime"
	"strconv"
	"strings"
	"syscall"
	"text/tabwriter"
	"time"

	"github.com/Ucok23/rekam/internal/api"
	"github.com/Ucok23/rekam/internal/db"
	"github.com/Ucok23/rekam/internal/email"
	"github.com/Ucok23/rekam/internal/engine"
	"github.com/Ucok23/rekam/internal/mcp"
)

// Set at build time: go build -ldflags "-X main.version=1.0.0 -X main.commit=abc1234 -X main.buildDate=2026-01-01"
var (
	version   = "dev"
	commit    = "unknown"
	buildDate = "unknown"
)

func main() {
	autoLoadEnv()
	if len(os.Args) < 2 {
		usage()
	}
	switch os.Args[1] {
	case "install":
		cmdInstall(os.Args[2:])
	case "serve":
		cmdServe(os.Args[2:])
	case "stop":
		cmdStop(os.Args[2:])
	case "restart":
		cmdRestart(os.Args[2:])
	case "status":
		cmdStatus(os.Args[2:])
	case "version", "--version", "-v":
		cmdVersion()
	case "key":
		cmdKey(os.Args[2:])
	case "grant":
		cmdGrant(os.Args[2:])
	default:
		fmt.Fprintf(os.Stderr, "unknown command: %s\n\n", os.Args[1])
		usage()
	}
}

// ── install ───────────────────────────────────────────────────────────────────

func cmdInstall(args []string) {
	fs := flag.NewFlagSet("install", flag.ExitOnError)
	dir := fs.String("dir", defaultInstallDir(), "directory for registry and memory files")
	name := fs.String("name", currentUser(), "your name (used as the human identity)")
	addr := fs.String("addr", defaultListenAddr(), "server listen address (e.g. :5000 or 8080)")
	budget := fs.Int("token-budget", 6000, "default token budget")
	yes := fs.Bool("yes", false, "skip confirmation prompt")
	fs.Parse(args)

	*addr = normalizeAddr(*addr)

	absDir, err := filepath.Abs(*dir)
	fatalf(err, "resolve dir")

	registryPath := filepath.Join(absDir, "registry.sqlite")
	memoryPath := filepath.Join(absDir, "default.rekam")
	envPath := filepath.Join(absDir, ".env")

	fmt.Printf("rekam install\n")
	fmt.Printf("  Directory:  %s\n", absDir)
	fmt.Printf("  Registry:   %s\n", registryPath)
	fmt.Printf("  Memory:     %s\n", memoryPath)
	fmt.Printf("  Identity:   %s (write=yes)\n", *name)
	fmt.Printf("  Listen:     %s\n\n", *addr)

	if !*yes {
		fmt.Print("Continue? [Y/n] ")
		scanner := bufio.NewScanner(os.Stdin)
		scanner.Scan()
		ans := strings.TrimSpace(strings.ToLower(scanner.Text()))
		if ans != "" && ans != "y" && ans != "yes" {
			fmt.Println("aborted")
			os.Exit(0)
		}
	}

	// 1. Create directory, user-writable only (0700) even if it already exists.
	if err := os.MkdirAll(absDir, 0700); err != nil {
		fatalf(err, "create directory")
	}
	if err := os.Chmod(absDir, 0700); err != nil {
		fatalf(err, "secure directory")
	}

	// 2. Open registry (creates it).
	reg, err := db.OpenRegistry(registryPath)
	fatalf(err, "open registry")

	// 3. Issue a human key.
	rawKey, err := generateKey()
	fatalf(err, "generate key")

	id, err := reg.Create(*name, rawKey, memoryPath, true)
	reg.Close()
	fatalf(err, "create identity")

	// 4. Touch the memory file (OpenMemory creates the schema).
	mdb, err := db.OpenMemory(memoryPath)
	fatalf(err, "initialise memory file")
	mdb.Close()

	// 5. Write .env file.
	envContent := fmt.Sprintf(`# rekam — generated by rekam install
REKAM_REGISTRY=%s
REKAM_ADDR=%s
REKAM_TOKEN_BUDGET=%d
REKAM_API_KEY=%s
`, registryPath, *addr, *budget, rawKey)
	if err := os.WriteFile(envPath, []byte(envContent), 0600); err != nil {
		fatalf(err, "write .env")
	}

	fmt.Printf("\nDone.\n\n")
	fmt.Printf("Identity:  %s (%s)\n", id.Name, id.ID)
	fmt.Printf("API Key:   %s\n", rawKey)
	fmt.Printf("           (also saved to %s)\n\n", envPath)

	// 6. Start the server in the background.
	if isSystemd() {
		if err := installUserService(absDir, *addr, envPath); err != nil {
			fmt.Printf("warning: could not install systemd service: %v\n", err)
			fmt.Printf("run manually: rekam serve\n")
		} else {
			fmt.Printf("Server running on %s\n", *addr)
			fmt.Printf("  systemctl --user status memory\n")
			fmt.Printf("  journalctl --user -u memory -f\n")
		}
	} else {
		if err := startBackground(absDir); err != nil {
			fmt.Printf("warning: could not start server: %v\n", err)
			fmt.Printf("run manually: rekam serve\n")
		} else {
			fmt.Printf("Server running on %s (pid: %s)\n", *addr, filepath.Join(absDir, "rekam.pid"))
		}
	}
}

// ── serve ─────────────────────────────────────────────────────────────────────

func cmdServe(args []string) {
	fs := flag.NewFlagSet("serve", flag.ExitOnError)
	registry := fs.String("registry", envOr("REKAM_REGISTRY", "registry.sqlite"), "path to registry.sqlite")
	addr := fs.String("addr", envOr("REKAM_ADDR", defaultListenAddr()), "listen address")
	budget := fs.Int("token-budget", envInt("REKAM_TOKEN_BUDGET", 6000), "default token budget (0=unlimited)")
	stdio := fs.Bool("stdio", false, "MCP stdio mode for Claude Desktop")
	mcpKey := fs.String("key", os.Getenv("REKAM_API_KEY"), "API key for MCP stdio mode")
	replicate := fs.Bool("replicate", envOr("REKAM_REPLICATE", "") != "", "replicate the registry and every tenant file to object storage, with S3 conditional-write write-lease coordination across nodes (see docs/plan-distributed-tenants.md)")
	replicateBucket := fs.String("replicate-bucket", os.Getenv("REKAM_REPLICATE_BUCKET"), "S3(-compatible) bucket for --replicate")
	replicatePrefix := fs.String("replicate-prefix", envOr("REKAM_REPLICATE_PREFIX", "rekam"), "key prefix within the replication bucket")
	replicateRegion := fs.String("replicate-region", envOr("REKAM_REPLICATE_REGION", "us-east-1"), "region for --replicate (ignored by most non-AWS S3-compatible stores)")
	replicateEndpoint := fs.String("replicate-endpoint", os.Getenv("REKAM_REPLICATE_ENDPOINT"), "custom S3-compatible endpoint (e.g. R2/MinIO) for --replicate")
	replicateOwner := fs.String("replicate-owner", os.Getenv("REKAM_NODE_URL"), "this node's own reachable base URL, recorded as the write-lease owner so a losing node can forward writes to it (see docs/plan-distributed-tenants.md §5)")
	fs.Parse(args)

	// managerOpts stays zero-value (no DefaultOpen override) when --replicate is
	// off — identical single-node behavior to before this flag existed.
	var managerOpts db.ManagerOptions
	registryPath := *registry
	usersDir := filepath.Join(filepath.Dir(*registry), "users")

	var repl *db.Replication
	if *replicate {
		if *replicateBucket == "" {
			fatalf(fmt.Errorf("--replicate-bucket (or REKAM_REPLICATE_BUCKET) is required with --replicate"), "replicate")
		}
		var err error
		repl, err = db.NewS3Replication(context.Background(), db.S3Config{
			Bucket:          *replicateBucket,
			Prefix:          *replicatePrefix,
			Region:          *replicateRegion,
			Endpoint:        *replicateEndpoint,
			AccessKeyID:     os.Getenv("AWS_ACCESS_KEY_ID"),
			SecretAccessKey: os.Getenv("AWS_SECRET_ACCESS_KEY"),
			Owner:           *replicateOwner,
		}, db.ReplicationOptions{})
		fatalf(err, "start replication")
		managerOpts.DefaultOpen = db.ReplicatedOpen(repl)
		// The registry itself is replicated and lease-gated the same as any
		// tenant file (see engine.requireRegistryPrimary). EnsureActive must
		// run before OpenRegistry so a fresh node restores it from the
		// replica rather than starting empty.
		if err := repl.EnsureActive(context.Background(), *registry, registryPath); err != nil {
			fatalf(err, "restore registry")
		}
	}

	reg, err := db.OpenRegistry(registryPath)
	fatalf(err, "open registry")
	defer reg.Close()

	*addr = normalizeAddr(*addr)

	var eng *engine.Engine
	if repl != nil {
		eng = engine.NewWithReplication(reg, *budget, managerOpts, repl, *registry)
	} else {
		eng = engine.NewWithManager(reg, *budget, managerOpts)
	}
	defer eng.Shutdown()
	defer func() {
		if repl != nil {
			repl.Close()
		}
	}()
	mcpSrv := mcp.NewServer(eng)

	// Directory for self-service signups' per-user .rekam files: a "users"
	// subdir alongside the registry. Created 0700 (user-private).
	if err := os.MkdirAll(usersDir, 0700); err != nil {
		fatalf(err, "create users directory")
	}
	bootstrapAdmin(eng, usersDir, *mcpKey)

	if *stdio {
		fmt.Fprintf(os.Stderr, "rekam %s: MCP stdio (registry: %s)\n", version, *registry)
		fatalf(mcpSrv.ServeStdio(*mcpKey), "mcp stdio")
		return
	}

	// The claude.ai MCP /authorize flow authenticates each user with their own
	// rekam email + password (no shared consent password), so the minted token is
	// scoped to that user's own memory store.
	mux := http.NewServeMux()
	apiSrv := api.NewServer(eng, *addr, os.Getenv("REKAM_ADMIN_KEY"), usersDir)

	// Whose forwarding headers to believe. The default is loopback, which
	// covers a Cloudflare Tunnel and a same-host reverse proxy; anyone whose
	// proxy is on another machine has to say so, because believing an
	// arbitrary peer's CF-Connecting-IP would let it mint a fresh rate-limit
	// bucket per request.
	if spec := os.Getenv("REKAM_TRUSTED_PROXIES"); spec != "" {
		prefixes, err := api.ParseTrustedProxies(spec)
		fatalf(err, "REKAM_TRUSTED_PROXIES")
		apiSrv.TrustProxies(prefixes)
	}
	// Confirm/reset/invite emails go out via Resend when both are set; with
	// either missing, apiSrv keeps its default email.Noop, and those flows
	// fall back to returning the token directly in the API response — see
	// internal/api/session.go's trySend.
	if resendKey, resendFrom := os.Getenv("RESEND_API_KEY"), os.Getenv("RESEND_FROM"); resendKey != "" && resendFrom != "" {
		apiSrv.SetEmailer(email.Resend{APIKey: resendKey, From: resendFrom})
		fmt.Fprintf(os.Stderr, "rekam: email delivery enabled via Resend (%s)\n", resendFrom)
	} else {
		fmt.Fprintf(os.Stderr, "rekam: WARNING: RESEND_API_KEY or RESEND_FROM not set — outgoing emails disabled, tokens will fall back to inline API responses (dev mode only)\n")
	}
	// The public docs corpus rendered read-only at /docs. It is built from
	// markdown shipped inside the binary (internal/docs/corpus), so it needs no
	// setup and is on by default; REKAM_DOCS=off turns it off, and
	// REKAM_DOCS_PATH moves the corpus file. A failure here is reported and
	// skipped rather than fatal: a docs problem should cost you the docs page,
	// not the server.
	// Managed only: the corpus is this project's own documentation, and
	// serving it opens the sole unauthenticated surface in the server.
	if api.Edition == "managed" && !strings.EqualFold(os.Getenv("REKAM_DOCS"), "off") {
		docsPath := os.Getenv("REKAM_DOCS_PATH")
		if docsPath == "" {
			docsPath = filepath.Join(usersDir, "docs.rekam")
		}
		if err := apiSrv.EnableDocs(docsPath); err != nil {
			fmt.Fprintf(os.Stderr, "rekam: public docs disabled: %v\n", err)
		} else {
			ins, upd, rem := apiSrv.DocsSyncCounts()
			fmt.Fprintf(os.Stderr, "rekam: public docs at /docs — %d added, %d updated, %d removed (%s)\n", ins, upd, rem, docsPath)
		}
	}
	// Tell the operator when a newer build exists — the only channel there is
	// for reaching a self-hosted instance about a security fix. Sends nothing
	// about this instance; see internal/updatecheck. REKAM_UPDATE_CHECK=off
	// disables it, in the same spirit as REKAM_DOCS=off.
	if !strings.EqualFold(os.Getenv("REKAM_UPDATE_CHECK"), "off") {
		go watchForUpdates(version, api.Edition)
	}

	mux.Handle("/", apiSrv.Handler())
	mcpHandler := mcpSrv.SSEHandler()
	mux.Handle("/mcp", mcpHandler)
	mux.Handle("/mcp/", mcpHandler)

	srv := &http.Server{Addr: *addr, Handler: mux}

	// Graceful shutdown on SIGINT / SIGTERM.
	stop := make(chan os.Signal, 1)
	signal.Notify(stop, syscall.SIGINT, syscall.SIGTERM)
	go func() {
		<-stop
		fmt.Fprintln(os.Stderr, "\nrekam: shutting down...")
		ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
		defer cancel()
		srv.Shutdown(ctx)
		eng.Shutdown() // drain & checkpoint open tenant handles
	}()

	// Name the edition: which routes exist is a build-time decision, so an
	// operator debugging a missing endpoint should not have to guess which
	// binary they are running.
	fmt.Fprintf(os.Stderr, "rekam %s (%s edition): listening on %s (REST + MCP SSE at /mcp)\n",
		version, api.Edition, *addr)
	if err := srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
		fatalf(err, "listen")
	}
}

// ── status ────────────────────────────────────────────────────────────────────

func cmdStatus(args []string) {
	fs := flag.NewFlagSet("status", flag.ExitOnError)
	registry := fs.String("registry", envOr("REKAM_REGISTRY", "registry.sqlite"), "path to registry.sqlite")
	addr := fs.String("addr", envOr("REKAM_ADDR", "http://localhost:5000"), "server address to ping")
	apiKey := fs.String("key", os.Getenv("REKAM_API_KEY"), "API key")
	fs.Parse(args)

	fmt.Printf("version:   %s (%s) built %s\n", version, commit, buildDate)
	fmt.Printf("registry:  %s\n", *registry)

	// Local registry info.
	reg, err := db.OpenRegistry(*registry)
	if err != nil {
		fmt.Printf("registry:  ERROR — %v\n", err)
	} else {
		ids, _ := reg.List()
		reg.Close()
		fmt.Printf("identities: %d\n", len(ids))
	}

	// Remote server ping.
	serverAddr := *addr
	if !strings.HasPrefix(serverAddr, "http") {
		serverAddr = "http://" + strings.TrimPrefix(serverAddr, ":")
		// handle ":5000" → "http://localhost:5000"
		if strings.HasPrefix(*addr, ":") {
			serverAddr = "http://localhost" + *addr
		}
	}
	pingURL := strings.TrimRight(serverAddr, "/") + "/catalog"

	client := &http.Client{Timeout: 3 * time.Second}
	req, _ := http.NewRequest("GET", pingURL, nil)
	if *apiKey != "" {
		req.Header.Set("Authorization", "Bearer "+*apiKey)
	}

	resp, err := client.Do(req)
	if err != nil {
		fmt.Printf("server:    offline (%v)\n", err)
		return
	}
	defer resp.Body.Close()

	var body map[string]any
	json.NewDecoder(resp.Body).Decode(&body)

	fmt.Printf("server:    online (%s)\n", serverAddr)
	if taxonomy, ok := body["taxonomy"].([]any); ok {
		fmt.Printf("taxonomy:  %d paths\n", len(taxonomy))
		for _, p := range taxonomy {
			fmt.Printf("           %v\n", p)
		}
	}
}

// watchForUpdates reports a newer release at startup and daily after that.
// Failures are silent: an instance with no outbound network must not log an
// error every day for a feature it did not ask for.
func watchForUpdates(current, edition string) {
	url := envOr("REKAM_UPDATE_URL", updatecheck.DefaultManifestURL)
	report := func() {
		ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
		defer cancel()
		m, err := updatecheck.Fetch(ctx, url)
		if err != nil {
			return
		}
		if msg := updatecheck.Compare(m, edition, current).Message(); msg != "" {
			fmt.Fprintf(os.Stderr, "rekam: %s\n", msg)
		}
	}
	report()
	t := time.NewTicker(24 * time.Hour)
	defer t.Stop()
	for range t.C {
		report()
	}
}

// ── version ───────────────────────────────────────────────────────────────────

func cmdVersion() {
	fmt.Printf("rekam %s\n", version)
	fmt.Printf("  edition: %s\n", api.Edition)
	fmt.Printf("  commit:  %s\n", commit)
	fmt.Printf("  built:   %s\n", buildDate)
	fmt.Printf("  go:      %s\n", runtime.Version())
	fmt.Printf("  os/arch: %s/%s\n", runtime.GOOS, runtime.GOARCH)

	// Asking `rekam version` is asking to be told, so this one is not
	// suppressed by REKAM_UPDATE_CHECK — but it still sends nothing.
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	m, err := updatecheck.Fetch(ctx, envOr("REKAM_UPDATE_URL", updatecheck.DefaultManifestURL))
	if err != nil {
		return
	}
	if msg := updatecheck.Compare(m, api.Edition, version).Message(); msg != "" {
		fmt.Printf("\n  %s\n", msg)
	}
}

// ── key ───────────────────────────────────────────────────────────────────────

func cmdKey(args []string) {
	if len(args) < 1 {
		fmt.Fprintln(os.Stderr, "usage: rekam key <issue|list|revoke>")
		os.Exit(1)
	}
	switch args[0] {
	case "issue":
		keyIssue(args[1:])
	case "list":
		keyList(args[1:])
	case "revoke":
		keyRevoke(args[1:])
	default:
		fmt.Fprintf(os.Stderr, "unknown key subcommand: %s\n", args[0])
		os.Exit(1)
	}
}

func keyIssue(args []string) {
	fs := flag.NewFlagSet("key issue", flag.ExitOnError)
	name := fs.String("name", "", "identity name (required)")
	memPath := fs.String("memory", "", "path to .rekam file (required)")
	write := fs.Bool("write", true, "grant write permission")
	registry := fs.String("registry", envOr("REKAM_REGISTRY", "registry.sqlite"), "registry path")
	fs.Parse(args)

	if *name == "" || *memPath == "" {
		fmt.Fprintln(os.Stderr, "error: --name and --memory are required")
		os.Exit(1)
	}

	rawKey, err := generateKey()
	fatalf(err, "generate key")

	reg, err := db.OpenRegistry(*registry)
	fatalf(err, "open registry")
	defer reg.Close()

	id, err := reg.Create(*name, rawKey, *memPath, *write)
	fatalf(err, "create identity")

	fmt.Printf("ID:      %s\n", id.ID)
	fmt.Printf("Name:    %s\n", id.Name)
	fmt.Printf("Memory:  %s\n", id.MemoryPath)
	fmt.Printf("Write:   %v\n", id.AllowWrite)
	fmt.Printf("\nAPI Key (shown once):\n  %s\n", rawKey)
}

func keyList(args []string) {
	fs := flag.NewFlagSet("key list", flag.ExitOnError)
	registry := fs.String("registry", envOr("REKAM_REGISTRY", "registry.sqlite"), "registry path")
	fs.Parse(args)

	reg, err := db.OpenRegistry(*registry)
	fatalf(err, "open registry")
	defer reg.Close()

	ids, err := reg.List()
	fatalf(err, "list identities")

	if len(ids) == 0 {
		fmt.Println("no identities")
		return
	}
	tw := tabwriter.NewWriter(os.Stdout, 0, 0, 2, ' ', 0)
	fmt.Fprintln(tw, "ID\tNAME\tWRITE\tMEMORY\tCREATED")
	for _, id := range ids {
		fmt.Fprintf(tw, "%s\t%s\t%v\t%s\t%s\n",
			id.ID, id.Name, id.AllowWrite,
			id.MemoryPath, id.CreatedAt.Format("2006-01-02"))
	}
	tw.Flush()
}

func keyRevoke(args []string) {
	fs := flag.NewFlagSet("key revoke", flag.ExitOnError)
	registry := fs.String("registry", envOr("REKAM_REGISTRY", "registry.sqlite"), "registry path")
	fs.Parse(args)

	if fs.NArg() < 1 {
		fmt.Fprintln(os.Stderr, "usage: rekam key revoke <identity-id>")
		os.Exit(1)
	}

	reg, err := db.OpenRegistry(*registry)
	fatalf(err, "open registry")
	defer reg.Close()

	fatalf(reg.Delete(fs.Arg(0)), "revoke")
	fmt.Printf("revoked %s\n", fs.Arg(0))
}

// ── grant (OAuth) ───────────────────────────────────────────────────────────────

func cmdGrant(args []string) {
	if len(args) < 1 {
		fmt.Fprintln(os.Stderr, "usage: rekam grant <list|revoke>")
		os.Exit(1)
	}
	switch args[0] {
	case "list":
		grantList(args[1:])
	case "revoke":
		grantRevoke(args[1:])
	default:
		fmt.Fprintf(os.Stderr, "unknown grant subcommand: %s\n", args[0])
		os.Exit(1)
	}
}

func grantList(args []string) {
	fs := flag.NewFlagSet("grant list", flag.ExitOnError)
	registry := fs.String("registry", envOr("REKAM_REGISTRY", "registry.sqlite"), "registry path")
	fs.Parse(args)

	reg, err := db.OpenRegistry(*registry)
	fatalf(err, "open registry")
	defer reg.Close()

	grants, err := reg.ListGrants()
	fatalf(err, "list grants")

	if len(grants) == 0 {
		fmt.Println("no grants")
		return
	}
	tw := tabwriter.NewWriter(os.Stdout, 0, 0, 2, ' ', 0)
	fmt.Fprintln(tw, "GRANT ID\tCLIENT\tSTATUS\tCREATED")
	for _, g := range grants {
		status := "active"
		if g.RevokedAt != nil {
			status = "revoked"
		}
		fmt.Fprintf(tw, "%s\t%s\t%s\t%s\n",
			g.ID, g.ClientID, status, g.CreatedAt.Format("2006-01-02"))
	}
	tw.Flush()
}

func grantRevoke(args []string) {
	fs := flag.NewFlagSet("grant revoke", flag.ExitOnError)
	registry := fs.String("registry", envOr("REKAM_REGISTRY", "registry.sqlite"), "registry path")
	fs.Parse(args)

	if fs.NArg() < 1 {
		fmt.Fprintln(os.Stderr, "usage: rekam grant revoke <grant-id>")
		os.Exit(1)
	}

	reg, err := db.OpenRegistry(*registry)
	fatalf(err, "open registry")
	defer reg.Close()

	fatalf(reg.RevokeGrant(fs.Arg(0)), "revoke grant")
	fmt.Printf("revoked grant %s\n", fs.Arg(0))
}

// ── helpers ───────────────────────────────────────────────────────────────────

func defaultInstallDir() string {
	if h, err := os.UserHomeDir(); err == nil {
		return filepath.Join(h, ".rekam")
	}
	return ".rekam"
}

func currentUser() string {
	if u, err := user.Current(); err == nil && u.Username != "" {
		return u.Username
	}
	return "user"
}

func isSystemd() bool {
	_, err := os.Stat("/run/systemd/system")
	return err == nil
}

// installUserService writes a ~/.config/systemd/user/rekam.service and enables it.
// No sudo required.
func installUserService(dir, _ string, envPath string) error {
	exe, err := os.Executable()
	if err != nil {
		return err
	}
	unitDir := filepath.Join(os.Getenv("HOME"), ".config", "systemd", "user")
	if err := os.MkdirAll(unitDir, 0755); err != nil {
		return err
	}
	unit := fmt.Sprintf(`[Unit]
Description=rekam OS
After=default.target

[Service]
ExecStart=%s serve
EnvironmentFile=%s
Restart=on-failure
WorkingDirectory=%s
KillMode=mixed
TimeoutStopSec=15

[Install]
WantedBy=default.target
`, exe, envPath, dir)
	unitPath := filepath.Join(unitDir, "rekam.service")
	if err := os.WriteFile(unitPath, []byte(unit), 0644); err != nil {
		return err
	}
	// daemon-reload, enable, start
	for _, args := range [][]string{
		{"--user", "daemon-reload"},
		{"--user", "enable", "--now", "memory"},
	} {
		cmd := exec.Command("systemctl", args...)
		cmd.Stderr = os.Stderr
		if err := cmd.Run(); err != nil {
			return fmt.Errorf("systemctl %v: %w", args, err)
		}
	}
	return nil
}

// startBackground launches `rekam serve` as a detached background process
// and writes its PID to dir/rekam.pid. Used on non-systemd hosts.
func startBackground(dir string) error {
	exe, err := os.Executable()
	if err != nil {
		return err
	}
	cmd := exec.Command(exe, "serve")
	cmd.Stdout = mustCreateFile(filepath.Join(dir, "server.log"))
	cmd.Stderr = cmd.Stdout
	cmd.SysProcAttr = &syscall.SysProcAttr{Setsid: true}
	if err := cmd.Start(); err != nil {
		return err
	}
	pid := fmt.Sprintf("%d\n", cmd.Process.Pid)
	return os.WriteFile(filepath.Join(dir, "rekam.pid"), []byte(pid), 0644)
}

// ── stop ──────────────────────────────────────────────────────────────────────

func cmdStop(args []string) {
	fs := flag.NewFlagSet("stop", flag.ExitOnError)
	dir := fs.String("dir", defaultInstallDir(), "install directory")
	fs.Parse(args)

	if isSystemd() {
		cmd := exec.Command("systemctl", "--user", "stop", "memory")
		cmd.Stdout = os.Stdout
		cmd.Stderr = os.Stderr
		fatalf(cmd.Run(), "systemctl stop")
		fmt.Println("stopped")
		return
	}

	fatalf(stopBackground(*dir), "stop")
	fmt.Println("stopped")
}

// ── restart ───────────────────────────────────────────────────────────────────

func cmdRestart(args []string) {
	fs := flag.NewFlagSet("restart", flag.ExitOnError)
	dir := fs.String("dir", defaultInstallDir(), "install directory")
	fs.Parse(args)

	if isSystemd() {
		cmd := exec.Command("systemctl", "--user", "restart", "memory")
		cmd.Stdout = os.Stdout
		cmd.Stderr = os.Stderr
		fatalf(cmd.Run(), "systemctl restart")
		fmt.Println("restarted")
		return
	}

	// Stop existing process (warn if the PID file is missing/invalid), then start anew.
	if err := stopBackground(*dir); err != nil {
		fmt.Printf("note: not stopping existing server: %v\n", err)
	}
	fatalf(startBackground(*dir), "start")
	fmt.Println("restarted")
}

// stopBackground kills the process recorded in dir/rekam.pid.
func stopBackground(dir string) error {
	pidPath := filepath.Join(dir, "rekam.pid")
	data, err := os.ReadFile(pidPath)
	if err != nil {
		return fmt.Errorf("no pid file found at %s (is the server running?)", pidPath)
	}
	pidStr := strings.TrimSpace(string(data))
	pid, err := strconv.Atoi(pidStr)
	if err != nil {
		return fmt.Errorf("invalid pid %q: %w", pidStr, err)
	}
	proc, err := os.FindProcess(pid)
	if err != nil {
		return fmt.Errorf("find process %d: %w", pid, err)
	}
	if err := proc.Signal(syscall.SIGTERM); err != nil {
		return fmt.Errorf("signal %d: %w", pid, err)
	}
	os.Remove(pidPath)
	return nil
}

func mustCreateFile(path string) *os.File {
	f, err := os.OpenFile(path, os.O_CREATE|os.O_APPEND|os.O_WRONLY, 0644)
	if err != nil {
		return os.Stderr
	}
	return f
}

// normalizeAddr ensures the address has a colon prefix (e.g. "5000" → ":5000").
func normalizeAddr(addr string) string {
	if addr != "" && !strings.Contains(addr, ":") {
		return ":" + addr
	}
	return addr
}

// autoLoadEnv loads ~/.rekam/.env if REKAM_REGISTRY is not already set.
// This lets `rekam serve` work without requiring the user to source the file.
func autoLoadEnv() {
	if os.Getenv("REKAM_REGISTRY") != "" {
		return
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return
	}
	envPath := filepath.Join(home, ".rekam", ".env")
	data, err := os.ReadFile(envPath)
	if err != nil {
		return
	}
	for line := range strings.SplitSeq(string(data), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		k, v, ok := strings.Cut(line, "=")
		if !ok {
			continue
		}
		if os.Getenv(k) == "" {
			os.Setenv(k, v)
		}
	}
}

// warnDefaultPassword logs a one-line warning when a login password is still the
// insecure built-in default, so a production deployment is nudged to set its own.
func warnDefaultPassword(envVar, value string) {
	if value == "test" {
		fmt.Fprintf(os.Stderr, "warning: %s is the default \"test\" — set it before exposing rekam publicly\n", envVar)
	}
}

// bootstrapAdmin ensures at least one admin account exists so the admin console
// is reachable. If none exists it prefers to adopt the master-key identity
// (REKAM_API_KEY) as the admin — attaching email + password + is_admin while
// keeping its existing memory — so an upgraded single-user install keeps its
// data reachable via the web login. Otherwise it creates a fresh admin account.
// Credentials come from REKAM_ADMIN_EMAIL (default admin@rekam.local) and
// REKAM_ADMIN_PASSWORD (default "test").
func bootstrapAdmin(eng *engine.Engine, usersDir, masterKey string) {
	exists, err := eng.AdminExists()
	if err != nil {
		fmt.Fprintf(os.Stderr, "warning: admin bootstrap check failed: %v\n", err)
		return
	}
	if exists {
		return
	}
	email := envOr("REKAM_ADMIN_EMAIL", "admin@rekam.local")
	password := envOr("REKAM_ADMIN_PASSWORD", "test")
	warnDefaultPassword("REKAM_ADMIN_PASSWORD", password)

	// Prefer adopting the existing master identity so its memory stays reachable.
	if masterKey != "" {
		if id, err := eng.PromoteToAdmin(masterKey, email, password); err == nil {
			fmt.Fprintf(os.Stderr, "adopted master identity %q as admin: %s (log in via the web UI)\n", id.Name, email)
			return
		}
	}

	memoryPath := filepath.Join(usersDir, "admin.rekam")
	if _, err := eng.CreateUser("admin", email, password, memoryPath, true, true); err != nil {
		fmt.Fprintf(os.Stderr, "warning: could not bootstrap admin account: %v\n", err)
		return
	}
	fmt.Fprintf(os.Stderr, "bootstrapped admin account: %s (log in via the web UI)\n", email)
}

func generateKey() (string, error) {
	b := make([]byte, 32)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return "mkey_" + hex.EncodeToString(b), nil
}

func fatalf(err error, msg string) {
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %s: %v\n", msg, err)
		os.Exit(1)
	}
}

func envOr(key, def string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return def
}

func envInt(key string, def int) int {
	if v := os.Getenv(key); v != "" {
		if n, err := strconv.Atoi(v); err == nil {
			return n
		}
	}
	return def
}

func usage() {
	fmt.Fprint(os.Stderr, `usage: rekam <command> [flags]

Commands:
  install     First-time setup — creates registry, memory file, and API key
  serve       Start the server (REST + MCP SSE)
  stop        Stop the background server
  restart     Restart the background server
  status      Show registry info and ping running server
  version     Show version info
  key issue   Issue a new API key
  key list    List all identities
  key revoke  Revoke an identity by ID
  grant list  List OAuth grants (issued via the /authorize flow)
  grant revoke Revoke an OAuth grant by grant ID

install flags:
  --dir          install directory        (default: ~/.rekam)
  --name         your name / identity     (default: current OS user)
  --addr         server listen address    (default: :5000)
  --token-budget default token budget     (default: 6000)
  --yes          skip confirmation

serve flags:
  --registry     path to registry.sqlite  (default: $REKAM_REGISTRY)
  --addr         listen address           (default: $REKAM_ADDR, else :5000
                 — 127.0.0.1:5000 in the solo edition, so a personal instance
                 is not on the network unless you say so)
  --token-budget token budget             (default: $REKAM_TOKEN_BUDGET or 6000)
  --stdio        MCP stdio mode (Claude Desktop)
  --key          API key for stdio mode   (default: $REKAM_API_KEY)
  --litefs-mount LiteFS mount root        (default: $REKAM_LITEFS_MOUNT, unset)
                 when set, registry + tenant files resolve under the mount
                 instead of as bare local paths — see docs/plan-distributed-tenants.md

stop/restart flags:
  --dir          install directory        (default: ~/.rekam)

status flags:
  --registry     path to registry.sqlite
  --addr         server address to ping   (default: http://localhost:5000)
  --key          API key for ping

key issue flags:
  --name         identity name (required)
  --memory       path to .rekam file (required)
  --write        grant write permission (default: true)
  --registry     registry path

Accounts / OAuth env vars (read by serve):
  REKAM_ADMIN_EMAIL     bootstrap admin email      (default admin@rekam.local)
  REKAM_ADMIN_PASSWORD  bootstrap admin password   (default "test" — override!)
  REKAM_ADMIN_KEY       legacy Bearer key for /admin/* (CLI/curl access)
  REKAM_API_KEY         master key for MCP stdio; adopted as the admin at bootstrap
  RESEND_API_KEY        Resend API key for confirm/reset/invite email (both required)
  RESEND_FROM           verified sender, e.g. "rekam <noreply@yourdomain>" (both required)

The claude.ai MCP /authorize flow authenticates each user with their own
rekam email + password; the minted token is scoped to that user's own store.
`)
	os.Exit(1)
}

// defaultListenAddr is where the server binds when nothing says otherwise.
//
// The solo edition binds loopback. It is the build a single person runs for
// themselves — often on a laptop or a home server — and the default should
// not put an authentication surface on whatever network they happen to be
// attached to. Reaching it from another machine is a deliberate act:
// `--addr 0.0.0.0:5000`, or REKAM_ADDR.
//
// Team and managed bind all interfaces, because being reached from elsewhere
// is the entire point of running them. (rekam.net binds loopback anyway, via
// REKAM_ADDR, because cloudflared is the only thing that should reach it.)
func defaultListenAddr() string {
	if api.Edition == "solo" {
		return "127.0.0.1:5000"
	}
	return ":5000"
}
